openapi: "3.0.0"
info:
  title: e-bazarek server backend
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /session-test:
    get:
      security:
        - cookieAuth: []
      operationId: TestSession
      responses:
        '200':
          description: OK

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSION_ID