openapi: "3.0.0"
info:
  title: e-bazarek server backend
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /session:
    get:
      security:
        - cookieAuth: []
      operationId: GetSession
      responses:
        '200':
          description: OK
    post:
      operationId: NewSession
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:                 
                - email                
                - password
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 50
                password:
                  type: string
                  minLength: 3
                  maxLength: 100
      responses:
        '200':
          description: OK
    delete:
      operationId: DestroySession
      responses:
        '200':
          description: OK
  /user:
    get:
      security:
        - cookieAuth: []
      operationId: GetUser
      responses:
        '200':
          description: OK
    post:
      operationId: CreateUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:                 
                - email                
                - password
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 50
                password:
                  type: string
                  minLength: 3
                  maxLength: 100
      responses:
        '200':
          description: OK
    put:
      operationId: UpdateUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                newPassword:
                  type: string
                  minLength: 3
                  maxLength: 100
                password:
                  type: string
                username:
                  type: string
                  maxLength: 50
                village:
                  type: string
                homeNumber:
                  type: string
                  maxLength: 10
                phone:
                  type: string
                  maxLength: 20
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSION_ID
